In [1]:
import numpy as np

# Function Tests for `ridge.pyx`

In [2]:
import pyximport; pyximport.install()
import ridge

data = np.genfromtxt("data/train_cleaned.csv", delimiter=",", skip_header=1)
data = np.delete(data, 0, 1)  # Delete ID column (b/c irrelevant to outcome var)
print(data.shape)

(1460, 348)


## `get_loss_gradient`

In [ ]:
example = data[7]
print(example)
weights = np.zeros(data.shape[1] - 1)
ridge.get_loss_gradient(example, weights, 3)

## `train`

In [ ]:
weights = np.zeros(data.shape[1] - 1)
example = data[1]


loss_gradient = ridge.get_loss_gradient(example, weights, 0)

print(loss_gradient)

## `test`

In [26]:
matrix = np.array([[1,0,0], [2,4,6], [3,3,3]])
print(matrix)

vec = np.array([2, 2, 2])
print(vec)

np.dot(matrix, vec)

np.delete(matrix, -1, 1)

[[1 0 0]
 [2 4 6]
 [3 3 3]]
[2 2 2]


array([[1, 0],
       [2, 4],
       [3, 3]])

# 1D Data

In [ ]:
a = np.array([1, 2, 3, 4])
list(range(a.shape[0]))

In [ ]:
example = np.array([1, 2, 3, 5, 8, 13])

feature_vector = np.delete(example, -1, 0)
response_value = example[-1]

print(feature_vector, "\n", response_value)

In [ ]:
vec1 = [1, 2, 3]
vec2 = [2, 2, 2]

# vec1 (dot) vec2 = 2 + 4 + 6 = 12
np.dot(vec1, vec2)

# Data Import (to NumPy array)
[np.genfromtext](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.io.genfromtxt.html)  
[np.delete](https://docs.scipy.org/doc/numpy/reference/generated/numpy.delete.html)

In [ ]:
data = np.genfromtxt("data/train_cleaned.csv", delimiter=",", skip_header=1)
data = np.delete(data, 0, 1)  # Delete ID column (b/c irrelevant to outcome var)

In [ ]:
data.shape[0]